### ISSUE TITLE
Run the train.py . I meet some questions.

### ISSUE THREAD

**Issue by gaoruihua111** [lightvector/KataGo#637]
Traceback (most recent call last):
  File "C:\Users\gaoruihua\Desktop\KataGo-master\python\train.py", line 699, in <module>
    maybe_reload_training_data()
  File "C:\Users\gaoruihua\Desktop\KataGo-master\python\train.py", line 630, in maybe_reload_training_data
    last_datainfo_row = datainfo["range"][1]
KeyError: 'range'

**Comment by lightvector** [comment]
shuffle.py is supposed to output the range of data rows used.
https://github.com/lightvector/KataGo/blob/master/python/shuffle.py#L639-L644

Perhaps you are pointing to the wrong directory or something has failed that cause this not to happen, or you forgot a step. You can manually inspect this file to see what it contains and/or check your logs and/or check again how you are shuffling the data.
