### ISSUE TITLE
Failed to execute script __main__

### ISSUE THREAD

**Issue by Cabu** [lightvector/KataGo#655]
When starting Katago (exe or from the zip) I receive an error message "Failed to execute \_\_main\_\_". Thinking that could it be because I don't have python, I installed the latest one (3.10.5 win amd64) without any change in the result.

Running DebugKaTrain I get the following messages:
```
 Traceback (most recent call last):
   File "katrain\__main__.py", line 97, in <module>
   File "c:\users\sande\anaconda3\envs\kt\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
   File "katrain\gui\badukpan.py", line 4, in <module>
 ModuleNotFoundError: No module named 'numpy'
[22248] Failed to execute script __main__
```

Installing numpy on my fresh python install (pip install numpy) didn't changed anything.

**Comment by Cabu** [comment]
Oups, not for Katago, but KataTrain
